spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/request_management}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    locations: classpath:db/migration,classpath:db/migration-prod
    ignore-migration-patterns: "*:missing"

  h2:
    console:
      enabled: false

logging:
  level:
    com.enoca: INFO

app:
  jwt:
    secret: ${JWT_SECRET}
  security:
    expose-api-docs: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
