CREATE TABLE requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(30)   NOT NULL,
    request_type   VARCHAR(30)   NOT NULL,
    requester_id   BIGINT        NOT NULL,
    status         VARCHAR(20)   NOT NULL,
    priority       VARCHAR(20)   NOT NULL,
    description    VARCHAR(1000) NOT NULL,
    submitted_at   TIMESTAMP,
    resolved_at    TIMESTAMP,
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP     NOT NULL,
    CONSTRAINT uk_requests_request_number UNIQUE (request_number),
    CONSTRAINT fk_requests_requester FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE INDEX idx_requests_requester ON requests (requester_id);
CREATE INDEX idx_requests_status ON requests (status);
CREATE INDEX idx_requests_type ON requests (request_type);

CREATE TABLE request_details (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detail_type VARCHAR(31) NOT NULL,
    request_id  BIGINT      NOT NULL,
    created_at  TIMESTAMP   NOT NULL,
    updated_at  TIMESTAMP   NOT NULL,
    CONSTRAINT uk_request_details_request UNIQUE (request_id),
    CONSTRAINT fk_request_details_request FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE leave_request_details (
    id         BIGINT      NOT NULL PRIMARY KEY,
    leave_type VARCHAR(30) NOT NULL,
    start_date DATE        NOT NULL,
    end_date   DATE        NOT NULL,
    total_days INTEGER     NOT NULL,
    CONSTRAINT fk_leave_details_parent FOREIGN KEY (id) REFERENCES request_details (id)
);

CREATE TABLE expense_request_details (
    id               BIGINT         NOT NULL PRIMARY KEY,
    amount           NUMERIC(12, 2) NOT NULL,
    expense_category VARCHAR(30)    NOT NULL,
    receipt_number   VARCHAR(50),
    CONSTRAINT fk_expense_details_parent FOREIGN KEY (id) REFERENCES request_details (id)
);

CREATE TABLE equipment_request_details (
    id             BIGINT         NOT NULL PRIMARY KEY,
    equipment_type VARCHAR(30)    NOT NULL,
    estimated_cost NUMERIC(12, 2) NOT NULL,
    quantity       INTEGER        NOT NULL,
    CONSTRAINT fk_equipment_details_parent FOREIGN KEY (id) REFERENCES request_details (id)
);

CREATE TABLE remote_work_request_details (
    id            BIGINT       NOT NULL PRIMARY KEY,
    start_date    DATE         NOT NULL,
    end_date      DATE         NOT NULL,
    work_location VARCHAR(150) NOT NULL,
    CONSTRAINT fk_remote_work_details_parent FOREIGN KEY (id) REFERENCES request_details (id)
);

CREATE TABLE access_permission_request_details (
    id            BIGINT       NOT NULL PRIMARY KEY,
    system_name   VARCHAR(100) NOT NULL,
    access_level  VARCHAR(20)  NOT NULL,
    justification VARCHAR(500) NOT NULL,
    CONSTRAINT fk_access_permission_details_parent FOREIGN KEY (id) REFERENCES request_details (id)
);
