CREATE TABLE approval_steps (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    BIGINT      NOT NULL,
    step_order    INTEGER     NOT NULL,
    approver_role VARCHAR(20) NOT NULL,
    approver_id   BIGINT,
    status        VARCHAR(20) NOT NULL,
    comment       VARCHAR(1000),
    action_date   TIMESTAMP,
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL,
    CONSTRAINT uk_approval_steps_request_order UNIQUE (request_id, step_order),
    CONSTRAINT fk_approval_steps_request FOREIGN KEY (request_id) REFERENCES requests (id),
    CONSTRAINT fk_approval_steps_approver FOREIGN KEY (approver_id) REFERENCES users (id)
);

CREATE INDEX idx_approval_steps_request ON approval_steps (request_id);
CREATE INDEX idx_approval_steps_approver_status ON approval_steps (approver_id, status);
